
DROP TABLE IF EXISTS ALUM_ASIG;
DROP TABLE IF EXISTS PROF_ASIG;
DROP TABLE IF EXISTS ALUMNO;
DROP TABLE IF EXISTS PROFESOR;
DROP TABLE IF EXISTS ASIGNATURA;

CREATE TABLE ALUMNO (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(25) NOT NULL ,
	apellido VARCHAR(50) NOT NULL ) ;

CREATE TABLE PROFESOR (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(25) NOT NULL ,
	apellido VARCHAR(50) NOT NULL );

CREATE TABLE ASIGNATURA (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(25) NOT NULL ,
	curso SMALLINT,
	ciclo VARCHAR(50));

CREATE TABLE ALUM_ASIG (
	ASIGNATURA INT,
	ALUMNO INT,
        FALTAS INT,
	PRIMARY KEY(ASIGNATURA,ALUMNO),
	FOREIGN KEY (ALUMNO) REFERENCES ALUMNO(id) ,
	FOREIGN KEY (ASIGNATURA) REFERENCES ASIGNATURA(id) );

CREATE TABLE PROF_ASIG (
	ASIGNATURA INT,
	PROFESOR INT,
        HORAS_SEMANALES INT,
	PRIMARY KEY(ASIGNATURA, PROFESOR),
	FOREIGN KEY (PROFESOR) REFERENCES PROFESOR(id),
	FOREIGN KEY (ASIGNATURA) REFERENCES ASIGNATURA(id));

INSERT INTO ALUMNO VALUES (
	NULL,
	'PEPE',
	'PEREZ');
INSERT INTO PROFESOR VALUES (
	NULL,
	'JUAN',
	'GUTIERREZ');
INSERT INTO ASIGNATURA VALUES (
	NULL,
	'Acceso a Datos',
	2,
	'DAM'
);

-- INSERT INTO PROF_ASIG VALUES ();
-- INSERT INTO PROF_ASIG VALUES ();

CREATE TABLE Usuarios(
	username VARCHAR(12) PRIMARY KEY,
        password VARCHAR(12) NOT NULL ,
	tipo SMALLINT);

INSERT INTO Usuarios VALUES(
    'admin',
    'admin',
    0);

SELECT * FROM Usuarios WHERE username='admin' and password=?